# Generated by Django 3.1.3 on 2020-11-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201107_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='father',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
