# Generated by Django 3.1.3 on 2020-11-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201107_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='org_id',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='org_id',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='sched_id',
            new_name='sched',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='org_id',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='warning',
            old_name='cam_id',
            new_name='cam',
        ),
    ]
