# Generated by Django 3.1.3 on 2020-11-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201107_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
    ]
