# Generated by Django 3.1.3 on 2020-11-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201109_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='email@nure.ua', max_length=100),
            preserve_default=False,
        ),
    ]
