# Generated by Django 3.1.3 on 2020-11-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='date',
            field=models.DateField(default='2020-11-18'),
            preserve_default=False,
        ),
    ]
