# Generated by Django 3.1.3 on 2020-11-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_warning_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='date',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='time',
        ),
        migrations.AddField(
            model_name='warning',
            name='datetime',
            field=models.DateTimeField(default='2020-11-19 15:25'),
            preserve_default=False,
        ),
    ]
